package T145.magistics;

import org.apache.logging.log4j.Logger;

import T145.magistics.config.ConfigHandler;
import T145.magistics.network.CommonProxy;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Magistics.MODID, name = Magistics.MODID, version = Magistics.VERSION, guiFactory = "T145.magistics.client.ModGuiFactory")
public class Magistics {
	public static final String MODID = "Magistics", VERSION = "$version";

	@Instance(MODID)
	public Magistics instance;

	@SidedProxy(serverSide = "T145.magistics.network.CommonProxy", clientSide = "T145.magistics.network.ClientProxy")
	public static CommonProxy proxy;

	@Metadata
	private ModMetadata metadata;

	public static ConfigHandler configHandler;
	public static Logger logger;

	private void loadMetadata() {
		logger.info("Loading metadata...");
		metadata.autogenerated = false;
		metadata.modId = MODID;
		metadata.name = MODID;
		metadata.version = VERSION;
		metadata.description = "Adding some logistics to Thaumcraft!";
		metadata.url = "https://github.com/T145/magistics";
		metadata.updateUrl = "https://github.com/T145/magistics/releases";
		metadata.authorList.add("T145");
		metadata.credits = "Special thanks to the fans who kept believing!";
		metadata.logoFile = "logo.png";
		logger.info("Loaded metadata!");
	}

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		configHandler = new ConfigHandler(event);
		logger = event.getModLog();
		loadMetadata();
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		FMLCommonHandler.instance().bus().register(configHandler);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		logger.info("Hello World!");
	}
}