package hu.hundevelopers.elysium.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelToothArmor extends ModelBiped
{
	ModelRenderer buttonR;
	ModelRenderer upperchestplate;
	ModelRenderer lowerchestplate;
	ModelRenderer body;
	ModelRenderer buttonL;
	ModelRenderer back;
	ModelRenderer head;
	ModelRenderer helmetsideR;
	ModelRenderer helmetsideL;
	ModelRenderer headback;
	ModelRenderer headtop;
	ModelRenderer helmet_point;
	ModelRenderer leftarm;
	ModelRenderer sholder1L;
	ModelRenderer finger2L;
	ModelRenderer armplate2L;
	ModelRenderer finger3L;
	ModelRenderer finger1L;
	ModelRenderer thumbL;
	ModelRenderer armplate1L;
	ModelRenderer finger4L;
	ModelRenderer armplate4L;
	ModelRenderer armplate3L;
	ModelRenderer legplate1R;
	ModelRenderer legplate2R;
	ModelRenderer belt;
	ModelRenderer belt_buckle;
	ModelRenderer upper_pants;
	ModelRenderer legL;
	ModelRenderer legR;
	ModelRenderer legplate1L;
	ModelRenderer legplate2L;
	ModelRenderer bootyplate2;
	ModelRenderer bootyplate1;
	ModelRenderer bootL;
	ModelRenderer knee1L;
	ModelRenderer knee2L;
	ModelRenderer toeL;
	ModelRenderer footL;
	ModelRenderer bootR;
	ModelRenderer knee1R;
	ModelRenderer knee2R;
	ModelRenderer toeR;
	ModelRenderer footR;
	ModelRenderer rightarm;
	ModelRenderer sholder1R;
	ModelRenderer finger2R;
	ModelRenderer armplate2R;
	ModelRenderer finger3R;
	ModelRenderer finger1R;
	ModelRenderer thumbR;
	ModelRenderer armplate1R;
	ModelRenderer finger4R;
	ModelRenderer armplate4R;
	ModelRenderer armplate3R;

	public ModelToothArmor(float scale)
	{
		super(scale, 0, 64, 128);
		
		textureWidth = 64;
		textureHeight = 128;
		
		buttonR = new ModelRenderer(this, 19, 54);
		buttonR.addBox(-4F, -2F, -3F, 2, 2, 1, scale);
		buttonR.setRotationPoint(0F, 0F, 0F);
		buttonR.setTextureSize(64, 128);
		buttonR.mirror = true;
		setRotation(buttonR, 0F, 0F, -0.7853982F);
		upperchestplate = new ModelRenderer(this, 15, 43);
		upperchestplate.addBox(-3.5F, 0F, -2F, 7, 5, 1, scale);
		upperchestplate.setRotationPoint(0F, 0F, 0F);
		upperchestplate.setTextureSize(64, 128);
		upperchestplate.mirror = true;
		setRotation(upperchestplate, -0.1919862F, 0F, 0F);
		lowerchestplate = new ModelRenderer(this, 15, 49);
		lowerchestplate.addBox(-3F, 4F, -3F, 6, 4, 1, scale);
		lowerchestplate.setRotationPoint(0F, 0F, 0F);
		lowerchestplate.setTextureSize(64, 128);
		lowerchestplate.mirror = true;
		setRotation(lowerchestplate, 0.1047198F, 0F, 0F);
		body = new ModelRenderer(this, 16, 16);
		body.addBox(-4F, 0F, -2F, 8, 9, 4, scale);
		body.setRotationPoint(0F, 0F, 0F);
		body.setTextureSize(64, 128);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		buttonL = new ModelRenderer(this, 19, 54);
		buttonL.addBox(2F, -2F, -3F, 2, 2, 1, scale);
		buttonL.setRotationPoint(0F, 0F, 0F);
		buttonL.setTextureSize(64, 128);
		buttonL.mirror = true;
		setRotation(buttonL, 0F, 0F, 0.7853982F);
		back = new ModelRenderer(this, 33, 85);
		back.addBox(-3.5F, 0F, 2F, 7, 5, 2, scale);
		back.setRotationPoint(0F, 0F, 0F);
		back.setTextureSize(64, 128);
		back.mirror = true;
		setRotation(back, -0.2617994F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8, scale);
		head.setRotationPoint(0F, 0F, 0F);
		head.setTextureSize(64, 128);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		helmetsideR = new ModelRenderer(this, 44, 0);
		helmetsideR.mirror = true;
		helmetsideR.addBox(-5F, -7F, -2.5F, 1, 7, 5, scale);
		helmetsideR.setRotationPoint(0F, 0F, 0F);
		helmetsideR.setTextureSize(64, 128);
		helmetsideR.mirror = true;
		setRotation(helmetsideR, 0F, 0F, 0F);
		helmetsideR.mirror = false;
		helmetsideL = new ModelRenderer(this, 44, 0);
		helmetsideL.addBox(4F, -7F, -2.5F, 1, 7, 5, scale);
		helmetsideL.setRotationPoint(0F, 0F, 0F);
		helmetsideL.setTextureSize(64, 128);
		helmetsideL.mirror = true;
		setRotation(helmetsideL, 0F, 0F, 0F);
		headback = new ModelRenderer(this, 52, 39);
		headback.addBox(-2.5F, -7F, 3.5F, 5, 7, 1, scale);
		headback.setRotationPoint(0F, 0F, 0F);
		headback.setTextureSize(64, 128);
		headback.mirror = true;
		setRotation(headback, 0F, 0F, 0F);
		headtop = new ModelRenderer(this, 40, 32);
		headtop.addBox(-3F, -8.5F, -3F, 6, 1, 6, scale);
		headtop.setRotationPoint(0F, 0F, 0F);
		headtop.setTextureSize(64, 128);
		headtop.mirror = true;
		setRotation(headtop, 0F, 0F, 0F);
		helmet_point = new ModelRenderer(this, 0, 95);
		helmet_point.addBox(-0.5F, -9.5F, -3.5F, 1, 6, 9, scale);
		helmet_point.setRotationPoint(0F, 0F, 0F);
		helmet_point.setTextureSize(64, 128);
		helmet_point.mirror = true;
		setRotation(helmet_point, 0F, 0F, 0F);
		leftarm = new ModelRenderer(this, 40, 16);
		leftarm.addBox(-1F, -2F, -2F, 4, 12, 4, scale);
		leftarm.setRotationPoint(0F, 0F, 0F);
		leftarm.setTextureSize(64, 128);
		leftarm.mirror = true;
		setRotation(leftarm, 0F, 0F, 0F);
		sholder1L = new ModelRenderer(this, 32, 40);
		sholder1L.addBox(-1F, -3F, -3.5F, 1, 6, 7, scale);
		sholder1L.setRotationPoint(0F, 0F, 0F);
		sholder1L.setTextureSize(64, 128);
		sholder1L.mirror = true;
		setRotation(sholder1L, 0F, 0F, 0.2617994F);
		finger2L = new ModelRenderer(this, 48, 80);
		finger2L.addBox(1.2F, 8.5F, -1.3F, 2, 2, 1, scale);
		finger2L.setRotationPoint(0F, 0F, 0F);
		finger2L.setTextureSize(64, 128);
		finger2L.mirror = true;
		setRotation(finger2L, 0F, 0F, 0F);
		armplate2L = new ModelRenderer(this, 32, 77);
		armplate2L.addBox(-3F, 5F, -2.5F, 3, 1, 5, scale);
		armplate2L.setRotationPoint(0F, 0F, 0F);
		armplate2L.setTextureSize(64, 128);
		armplate2L.mirror = true;
		setRotation(armplate2L, 0F, 0F, -0.7853982F);
		finger3L = new ModelRenderer(this, 48, 80);
		finger3L.addBox(1.2F, 8.5F, 0F, 2, 2, 1, scale);
		finger3L.setRotationPoint(0F, 0F, 0F);
		finger3L.setTextureSize(64, 128);
		finger3L.mirror = true;
		setRotation(finger3L, 0F, 0F, 0F);
		finger1L = new ModelRenderer(this, 48, 80);
		finger1L.addBox(1.2F, 8.5F, -2.5F, 2, 2, 1, scale);
		finger1L.setRotationPoint(0F, 0F, 0F);
		finger1L.setTextureSize(64, 128);
		finger1L.mirror = true;
		setRotation(finger1L, 0F, 0F, 0F);
		thumbL = new ModelRenderer(this, 48, 76);
		thumbL.addBox(0F, 8.5F, -2.5F, 1, 2, 2, scale);
		thumbL.setRotationPoint(0F, 0F, 0F);
		thumbL.setTextureSize(64, 128);
		thumbL.mirror = true;
		setRotation(thumbL, 0F, 0F, 0F);
		armplate1L = new ModelRenderer(this, 32, 70);
		armplate1L.addBox(0.5F, 1F, -2.5F, 3, 2, 5, scale);
		armplate1L.setRotationPoint(0F, 0F, 0F);
		armplate1L.setTextureSize(64, 128);
		armplate1L.mirror = true;
		setRotation(armplate1L, 0F, 0F, 0F);
		finger4L = new ModelRenderer(this, 48, 80);
		finger4L.addBox(1.2F, 8.5F, 1.3F, 2, 2, 1, scale);
		finger4L.setRotationPoint(0F, 0F, 0F);
		finger4L.setTextureSize(64, 128);
		finger4L.mirror = true;
		setRotation(finger4L, 0F, 0F, 0F);
		armplate4L = new ModelRenderer(this, 48, 70);
		armplate4L.addBox(2.4F, 7.2F, -2.5F, 1, 1, 5, scale);
		armplate4L.setRotationPoint(0F, 0F, 0F);
		armplate4L.setTextureSize(64, 128);
		armplate4L.mirror = true;
		setRotation(armplate4L, 0F, 0F, 0.0349066F);
		armplate3L = new ModelRenderer(this, 48, 70);
		armplate3L.addBox(2.4F, 6F, -2.5F, 1, 1, 5, scale);
		armplate3L.setRotationPoint(0F, 0F, 0F);
		armplate3L.setTextureSize(64, 128);
		armplate3L.mirror = true;
		setRotation(armplate3L, 0F, 0F, 0F);
		legplate1R = new ModelRenderer(this, 0, 56);
		legplate1R.mirror = true;
		legplate1R.addBox(-2.5F, -0.5F, -3F, 2, 3, 6, scale);
		legplate1R.setRotationPoint(0F, 0F, 0F);
		legplate1R.setTextureSize(64, 128);
		legplate1R.mirror = true;
		setRotation(legplate1R, 0F, 0F, 0.1745329F);
		legplate1R.mirror = false;
		legplate2R = new ModelRenderer(this, 0, 65);
		legplate2R.mirror = true;
		legplate2R.addBox(-2F, 2.5F, -2.5F, 2, 2, 5, scale);
		legplate2R.setRotationPoint(0F, 0F, 0F);
		legplate2R.setTextureSize(64, 128);
		legplate2R.mirror = true;
		setRotation(legplate2R, 0F, 0F, 0.1745329F);
		legplate2R.mirror = false;
		belt = new ModelRenderer(this, 0, 36);
		belt.addBox(-4.5F, 10F, -2.5F, 9, 1, 5, scale);
		belt.setRotationPoint(0F, 0F, 0F);
		belt.setTextureSize(64, 128);
		belt.mirror = true;
		setRotation(belt, 0F, 0F, 0F);
		belt_buckle = new ModelRenderer(this, 23, 36);
		belt_buckle.addBox(-1.5F, 10.5F, -1.7F, 3, 3, 1, scale);
		belt_buckle.setRotationPoint(0F, 0F, 0F);
		belt_buckle.setTextureSize(64, 128);
		belt_buckle.mirror = true;
		setRotation(belt_buckle, -0.122173F, 0F, 0F);
		upper_pants = new ModelRenderer(this, 16, 29);
		upper_pants.addBox(-4F, 9F, -2F, 8, 3, 4, scale);
		upper_pants.setRotationPoint(0F, 0F, 0F);
		upper_pants.setTextureSize(64, 128);
		upper_pants.mirror = true;
		setRotation(upper_pants, 0F, 0F, 0F);
		legL = new ModelRenderer(this, 0, 16);
		legL.addBox(-2F, 0F, -2F, 4, 5, 4, scale);
		legL.setRotationPoint(0F, 0F, 0F);
		legL.setTextureSize(64, 128);
		legL.mirror = true;
		setRotation(legL, 0F, 0F, 0F);
		legR = new ModelRenderer(this, 0, 16);
		legR.mirror = true;
		legR.addBox(-2F, 0F, -2F, 4, 5, 4, scale);
		legR.setRotationPoint(0F, 0F, 0F);
		legR.setTextureSize(64, 128);
		legR.mirror = true;
		setRotation(legR, 0F, 0F, 0F);
		legR.mirror = false;
		legplate1L = new ModelRenderer(this, 0, 56);
		legplate1L.addBox(0.5F, -0.5F, -3F, 2, 3, 6, scale);
		legplate1L.setRotationPoint(0F, 0F, 0F);
		legplate1L.setTextureSize(64, 128);
		legplate1L.mirror = true;
		setRotation(legplate1L, 0F, 0F, -0.1745329F);
		legplate2L = new ModelRenderer(this, 0, 65);
		legplate2L.addBox(0F, 2.5F, -2.5F, 2, 2, 5, scale);
		legplate2L.setRotationPoint(0F, 0F, 0F);
		legplate2L.setTextureSize(64, 128);
		legplate2L.mirror = true;
		setRotation(legplate2L, 0F, 0F, -0.1745329F);
		bootyplate2 = new ModelRenderer(this, 16, 65);
		bootyplate2.addBox(-2.5F, 15F, -1F, 5, 1, 1, scale);
		bootyplate2.setRotationPoint(0F, 0F, 0F);
		bootyplate2.setTextureSize(64, 128);
		bootyplate2.mirror = true;
		setRotation(bootyplate2, 0.2617994F, 0F, 0F);
		bootyplate1 = new ModelRenderer(this, 16, 60);
		bootyplate1.addBox(-3.5F, 11F, -1F, 7, 4, 1, scale);
		bootyplate1.setRotationPoint(0F, 0F, 0F);
		bootyplate1.setTextureSize(64, 128);
		bootyplate1.mirror = true;
		setRotation(bootyplate1, 0.2617994F, 0F, 0F);
		bootL = new ModelRenderer(this, 0, 25);
		bootL.addBox(-2F, 5F, -2F, 4, 7, 4, scale);
		bootL.setRotationPoint(0F, 0F, 0F);
		bootL.setTextureSize(64, 128);
		bootL.mirror = true;
		setRotation(bootL, 0F, 0F, 0F);
		knee1L = new ModelRenderer(this, 0, 75);
		knee1L.addBox(-1.5F, 2F, -6F, 3, 2, 2, scale);
		knee1L.setRotationPoint(0F, 0F, 0F);
		knee1L.setTextureSize(64, 128);
		knee1L.mirror = true;
		setRotation(knee1L, 0.7853982F, 0F, 0F);
		knee2L = new ModelRenderer(this, 0, 79);
		knee2L.addBox(-1F, 5F, -4.1F, 2, 2, 1, scale);
		knee2L.setRotationPoint(0F, 0F, 0F);
		knee2L.setTextureSize(64, 128);
		knee2L.mirror = true;
		setRotation(knee2L, 0.2792527F, 0F, 0F);
		toeL = new ModelRenderer(this, 0, 85);
		toeL.addBox(-1F, 11F, -3F, 2, 1, 1, scale);
		toeL.setRotationPoint(0F, 0F, 0F);
		toeL.setTextureSize(64, 128);
		toeL.mirror = true;
		setRotation(toeL, 0F, 0F, 0F);
		footL = new ModelRenderer(this, 0, 82);
		footL.addBox(-1.5F, 9F, 6F, 3, 1, 1, scale);
		footL.setRotationPoint(0F, 0F, 0F);
		footL.setTextureSize(64, 128);
		footL.mirror = true;
		setRotation(footL, -0.7853982F, 0F, 0F);
		bootR = new ModelRenderer(this, 0, 25);
		bootR.mirror = true;
		bootR.addBox(-2F, 5F, -2F, 4, 7, 4, scale);
		bootR.setRotationPoint(0F, 0F, 0F);
		bootR.setTextureSize(64, 128);
		bootR.mirror = true;
		setRotation(bootR, 0F, 0F, 0F);
		bootR.mirror = false;
		knee1R = new ModelRenderer(this, 0, 75);
		knee1R.mirror = true;
		knee1R.addBox(-1.5F, 2F, -6F, 3, 2, 2, scale);
		knee1R.setRotationPoint(0F, 0F, 0F);
		knee1R.setTextureSize(64, 128);
		knee1R.mirror = true;
		setRotation(knee1R, 0.7853982F, 0F, 0F);
		knee1R.mirror = false;
		knee2R = new ModelRenderer(this, 0, 79);
		knee2R.mirror = true;
		knee2R.addBox(-1F, 5F, -4.1F, 2, 2, 1, scale);
		knee2R.setRotationPoint(0F, 0F, 0F);
		knee2R.setTextureSize(64, 128);
		knee2R.mirror = true;
		setRotation(knee2R, 0.2792527F, 0F, 0F);
		knee2R.mirror = false;
		toeR = new ModelRenderer(this, 0, 85);
		toeR.mirror = true;
		toeR.addBox(-1F, 11F, -3F, 2, 1, 1, scale);
		toeR.setRotationPoint(0F, 0F, 0F);
		toeR.setTextureSize(64, 128);
		toeR.mirror = true;
		setRotation(toeR, 0F, 0F, 0F);
		toeR.mirror = false;
		footR = new ModelRenderer(this, 0, 82);
		footR.mirror = true;
		footR.addBox(-1.5F, 9F, 6F, 3, 1, 1, scale);
		footR.setRotationPoint(0F, 0F, 0F);
		footR.setTextureSize(64, 128);
		footR.mirror = true;
		setRotation(footR, -0.7853982F, 0F, 0F);
		footR.mirror = false;
		rightarm = new ModelRenderer(this, 40, 16);
		rightarm.mirror = true;
		rightarm.addBox(-3F, -2F, -2F, 4, 12, 4, scale);
		rightarm.setRotationPoint(0F, 0F, 0F);
		rightarm.setTextureSize(64, 128);
		rightarm.mirror = true;
		setRotation(rightarm, 0F, 0F, 0F);
		rightarm.mirror = false;
		sholder1R = new ModelRenderer(this, 32, 40);
		sholder1R.mirror = true;
		sholder1R.addBox(0F, -3F, -3.5F, 1, 6, 7, scale);
		sholder1R.setRotationPoint(0F, 0F, 0F);
		sholder1R.setTextureSize(64, 128);
		sholder1R.mirror = true;
		setRotation(sholder1R, 0F, 0F, -0.2617994F);
		sholder1R.mirror = false;
		finger2R = new ModelRenderer(this, 48, 80);
		finger2R.mirror = true;
		finger2R.addBox(-3.2F, 8.5F, -1.3F, 2, 2, 1, scale);
		finger2R.setRotationPoint(0F, 0F, 0F);
		finger2R.setTextureSize(64, 128);
		finger2R.mirror = true;
		setRotation(finger2R, 0F, 0F, 0F);
		finger2R.mirror = false;
		armplate2R = new ModelRenderer(this, 32, 77);
		armplate2R.addBox(0F, 5F, -2.5F, 3, 1, 5, scale);
		armplate2R.setRotationPoint(0F, 0F, 0F);
		armplate2R.setTextureSize(64, 128);
		armplate2R.mirror = true;
		setRotation(armplate2R, 0F, 0F, 0.7853982F);
		finger3R = new ModelRenderer(this, 48, 80);
		finger3R.mirror = true;
		finger3R.addBox(-3.2F, 8.5F, 0F, 2, 2, 1, scale);
		finger3R.setRotationPoint(0F, 0F, 0F);
		finger3R.setTextureSize(64, 128);
		finger3R.mirror = true;
		setRotation(finger3R, 0F, 0F, 0F);
		finger3R.mirror = false;
		finger1R = new ModelRenderer(this, 48, 80);
		finger1R.mirror = true;
		finger1R.addBox(-3.2F, 8.5F, -2.5F, 2, 2, 1, scale);
		finger1R.setRotationPoint(0F, 0F, 0F);
		finger1R.setTextureSize(64, 128);
		finger1R.mirror = true;
		setRotation(finger1R, 0F, 0F, 0F);
		finger1R.mirror = false;
		thumbR = new ModelRenderer(this, 48, 76);
		thumbR.mirror = true;
		thumbR.addBox(-1F, 8.5F, -2.5F, 1, 2, 2, scale);
		thumbR.setRotationPoint(0F, 0F, 0F);
		thumbR.setTextureSize(64, 128);
		thumbR.mirror = true;
		setRotation(thumbR, 0F, 0F, 0F);
		thumbR.mirror = false;
		armplate1R = new ModelRenderer(this, 32, 70);
		armplate1R.mirror = true;
		armplate1R.addBox(-3.5F, 1F, -2.5F, 3, 2, 5, scale);
		armplate1R.setRotationPoint(0F, 0F, 0F);
		armplate1R.setTextureSize(64, 128);
		armplate1R.mirror = true;
		setRotation(armplate1R, 0F, 0F, 0F);
		armplate1R.mirror = false;
		finger4R = new ModelRenderer(this, 48, 80);
		finger4R.mirror = true;
		finger4R.addBox(-3.2F, 8.5F, 1.3F, 2, 2, 1, scale);
		finger4R.setRotationPoint(0F, 0F, 0F);
		finger4R.setTextureSize(64, 128);
		finger4R.mirror = true;
		setRotation(finger4R, 0F, 0F, 0F);
		finger4R.mirror = false;
		armplate4R = new ModelRenderer(this, 48, 70);
		armplate4R.mirror = true;
		armplate4R.addBox(-3.4F, 7.2F, -2.5F, 1, 1, 5, scale);
		armplate4R.setRotationPoint(0F, 0F, 0F);
		armplate4R.setTextureSize(64, 128);
		armplate4R.mirror = true;
		setRotation(armplate4R, 0F, 0F, -0.0349066F);
		armplate4R.mirror = false;
		armplate3R = new ModelRenderer(this, 48, 70);
		armplate3R.mirror = true;
		armplate3R.addBox(-3.4F, 6F, -2.5F, 1, 1, 5, scale);
		armplate3R.setRotationPoint(0F, 0F, 0F);
		armplate3R.setTextureSize(64, 128);
		armplate3R.mirror = true;
		setRotation(armplate3R, 0F, 0F, 0F);
		armplate3R.mirror = false;
		
		//Head
		this.bipedHead.cubeList.clear();
		this.bipedHeadwear.cubeList.clear();
		this.bipedHead.addChild(head);
		this.bipedHead.addChild(helmetsideL);
		this.bipedHead.addChild(helmetsideR);
		this.bipedHead.addChild(headback);
		this.bipedHead.addChild(headtop);
		this.bipedHead.addChild(helmet_point);
		
		//Chest
		this.bipedBody.cubeList.clear();//////do not duplicate
		this.bipedBody.addChild(buttonL);
		this.bipedBody.addChild(buttonR);
		this.bipedBody.addChild(upperchestplate);
		this.bipedBody.addChild(lowerchestplate);
		this.bipedBody.addChild(body);
		this.bipedBody.addChild(back);

		//Left Arm
		this.bipedLeftArm.cubeList.clear();
		this.bipedLeftArm.addChild(leftarm);
		this.bipedLeftArm.addChild(sholder1L);
		this.bipedLeftArm.addChild(finger1L);
		this.bipedLeftArm.addChild(finger2L);
		this.bipedLeftArm.addChild(finger3L);
		this.bipedLeftArm.addChild(finger4L);
		this.bipedLeftArm.addChild(armplate1L);
		this.bipedLeftArm.addChild(armplate2L);
		this.bipedLeftArm.addChild(armplate3L);
		this.bipedLeftArm.addChild(armplate4L);
		this.bipedLeftArm.addChild(thumbL);

		//Right Arm
		this.bipedRightArm.cubeList.clear();
		this.bipedRightArm.addChild(rightarm);
		this.bipedRightArm.addChild(sholder1R);
		this.bipedRightArm.addChild(finger1R);
		this.bipedRightArm.addChild(finger2R);
		this.bipedRightArm.addChild(finger3R);
		this.bipedRightArm.addChild(finger4R);
		this.bipedRightArm.addChild(armplate1R);
		this.bipedRightArm.addChild(armplate2R);
		this.bipedRightArm.addChild(armplate3R);
		this.bipedRightArm.addChild(armplate4R);
		this.bipedRightArm.addChild(thumbR);
		
		//Pants
		this.bipedBody.addChild(belt);
		this.bipedBody.addChild(belt_buckle);
		this.bipedBody.addChild(upper_pants);
		this.bipedBody.addChild(bootyplate1);
		this.bipedBody.addChild(bootyplate2);
		
		this.bipedBody.addChild(legL);
		this.bipedBody.addChild(legR);
		
		//Boots
		this.bipedRightLeg.cubeList.clear();
		this.bipedRightLeg.addChild(bootR);
		this.bipedRightLeg.addChild(knee1R);
		this.bipedRightLeg.addChild(knee2R);
		this.bipedRightLeg.addChild(toeR);
		this.bipedRightLeg.addChild(footR);
		this.bipedRightLeg.addChild(legplate1R);
		this.bipedRightLeg.addChild(legplate2R);
		
		this.bipedLeftLeg.cubeList.clear();
		this.bipedLeftLeg.addChild(bootL);
		this.bipedLeftLeg.addChild(knee1L);
		this.bipedLeftLeg.addChild(knee2L);
		this.bipedLeftLeg.addChild(toeL);
		this.bipedLeftLeg.addChild(footL);
		this.bipedLeftLeg.addChild(legplate1L);
		this.bipedLeftLeg.addChild(legplate2L);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
//		if(entity instanceof EntityHero || entity instanceof EntitySkeleton || entity instanceof EntityZombie)
//			setRotationAnglesHero(f, f1, f2, f3, f4, f5, entity);
//		else
			setRotationAngles(f5, f, f1, f2, f3, f4, entity);
		
		float a = MathHelper.abs(f * 0.6662F) * 1.4F * f1;
		float b = MathHelper.abs(f * 0.6662F + 3.141593F) * 1.4F * f1;
		float c = Math.min(a, b);

		this.belt_buckle.rotateAngleX = c - 0.10472F;
		this.bootyplate1.rotateAngleX = this.bootyplate2.rotateAngleX = -c + 0.10472F;
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
