package T145.magistics.core;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import T145.magistics.api.internal.IModProxy;
import T145.magistics.api.internal.IProxy;
import T145.magistics.common.lib.CreativeTabMagistics;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Magistics.ID, name = Magistics.NAME, version = Magistics.VERSION)
public class Magistics implements IModProxy {

	public static final String ID = "magistics";
	public static final String NAME = "Magistics";
	public static final String VERSION = "$version";
	public static final String SERVER_PROXY = "T145.magistics.common.CommonProxy";
	public static final String CLIENT_PROXY = "T145.magistics.client.ClientProxy";
	public static final Logger LOG = LogManager.getLogger(NAME);
	public static final CreativeTabs TAB = new CreativeTabMagistics();

	@Instance(ID)
	public static Magistics instance;

	@SidedProxy(serverSide = SERVER_PROXY, clientSide = CLIENT_PROXY)
	public static IProxy proxy;

	@Metadata
	private ModMetadata meta;

	@Override
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		meta.authorList.add("T145");
		meta.autogenerated = false;
		meta.credits = "Thanks to everyone who kept believing!";
		meta.description = "Logistical magic!";
		meta.logoFile = "logo.png";
		meta.modId = ID;
		meta.name = NAME;
		meta.url = "https://github.com/T145/magistics";
		meta.useDependencyInformation = false;
		meta.version = VERSION;
		proxy.preInit(event);
	}

	@Override
	@EventHandler
	public void init(FMLInitializationEvent event) {
		proxy.init(event);
	}

	@Override
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}
}